app:
  name: svc
  template:
    oidc_client_id: "ONECX_OIDC_CLIENT_CLIENT_ID"
  image:
    repository: "onecx/onecx-tenant-svc"
  db:
    enabled: true
  operator:
    microservice:
      spec:
        description: OneCX Tenant Backend Service
        name: OneCX Tenant SVC