---
openapi: 3.0.3
info:
  title: onecx tenant export import service V1
  description: This API provides endpoints to import tenants by the onecx operator only
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: tenantExportImport
    description: Importing tenants
paths:
  /exim/v1/tenants/operator:
    post:
      security:
        - oauth2: [ ocx-tn:write ]
      tags:
        - tenantExportImport
      description: Import tenants by the operator only
      operationId: operatorImportTenants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantsSnapshot'
      responses:
        "200":
          description: Tenants imported successfully
        "409":
          description: The request could not be fully completed due to a conflict with the current state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EximProblemDetailResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EximProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-tn:write: Grants write access
  schemas:
    TenantsSnapshot:
      type: object
      properties:
        id:
          type: string
          minLength: 10
          description: ID of the request
        created:
          $ref: '#/components/schemas/OffsetDateTime'
        tenants:
          type: object
          nullable: false
          description: tenant id
          additionalProperties:
            $ref: '#/components/schemas/EximTenant'
    EximTenant:
      type: object
      nullable: false
      description: tenant data
      properties:
        description:
          type: string
        orgId:
          type: string
    EximProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/EximProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/EximProblemDetailInvalidParam'
    EximProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    EximProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00