openapi: "3.0.2"
info:
  title: onecx-tenant internal service
  description: This API provides endpoints to manage Tenants
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: tenantInternal
    description: Managing Tenants
paths:
  /internal/tenants/search:
      post:
        security:
          - oauth2: [ ocx-tn:all, ocx-tn:read ]
        tags:
          - tenantInternal
        description: Search tenants by search criteria
        operationId: searchTenants
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSearchCriteria'
        responses:
          "200":
            description: Tenant search results retrieved successfully
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/TenantPageResult"
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/tenants:
      post:
        security:
          - oauth2: [ ocx-tn:all, ocx-tn:write ]
        tags:
          - tenantInternal
        summary: Create a new tenant
        operationId: createTenant
        requestBody:
          required: true
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateTenantRequest'
        responses:
          "201":
            description: Tenant created successfully
            headers:
              Location:
                required: true
                schema:
                  type: string
                  format: url
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ProblemDetailResponse'
          "404":
            description: Tenant not found
  /internal/tenants/{id}:
      get:
        security:
          - oauth2: [ ocx-tn:all, ocx-tn:read ]
        tags:
          - tenantInternal
        summary: Get Tenant map by its id
        operationId: getTenant
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        responses:
          "200":
            description: Tenants retrieved successfully
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/Tenant"
          "404":
            description: Tenant not found
      put:
        security:
          - oauth2: [ ocx-tn:all, ocx-tn:write ]
        tags:
          - tenantInternal
        summary: Update a tenant by its id
        operationId: updateTenant
        parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UpdateTenantRequest'
        responses:
          "200":
            description: Tenant updated successfully
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/Tenant"
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ProblemDetailResponse'
          "404":
            description: Tenant not found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-tn:all: Grants access to all operations
            ocx-tn:read: Grants read access
            ocx-tn:write: Grants write access
  schemas:
    TenantSearchCriteria:
      type: object
      properties:
        orgId:
          nullable: true
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    CreateTenantRequest:
      type: object
      required:
        - orgId
        - tenantId
      properties:
        orgId:
          type: string
          description: Id of the organization
        tenantId:
          type: string
          description: Id of the tenant
        description:
          type: string
          description: Description of the tenant
    UpdateTenantRequest:
      type: object
      required:
        - orgId
      properties:
        orgId:
          type: string
          description: Id of the organization
        description:
          type: string
          description: Description of the tenant
    TenantPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Tenant'
    Tenant:
      type: object
      properties:
        modificationCount:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        id:
          type: string
        orgId:
          type: string
          description: Id of the organization
        tenantId:
          type: string
          description: Id of the tenant
        description:
          type: string
          description: Description of the tenant
        operator:
          type: boolean
          default: false
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00