---
openapi: 3.0.3
info:
  title: onecx-tenant data import service V1
  description: This API provides endpoints for data import on application start
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/tenant:
    post:
      security:
        - oauth2: [ ocx-tn:write ]
      operationId: importTenant
      description: Import tenants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-tn:write: Grants write access
  schemas:
    DataImport:
      type: object
      properties:
        tenants:
          $ref: '#/components/schemas/DataImportTenants'
    DataImportTenants:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportTenant'
    DataImportTenant:
      type: object
      required:
        - orgId
      properties:
        orgId:
          type: string
        description:
          type: string