---
openapi: 3.0.3
info:
  title: onecx-tenant internal image service
  description: This API provides endpoints to manage tenant images
  version: 1.0.0
servers:
  - url: "http://onecx-tenant-svc:8080"
tags:
  - name: imagesInternal
    description: Managing Images
paths:
  /internal/images/{refId}/{refType}:
    post:
      security:
        - oauth2: [ ocx-tn:all, ocx-tn:write ]
      tags:
        - imagesInternal
      description: Upload an image by its reference id and type
      parameters:
        - in: header
          name: Content-Length
          required: true
          schema:
            minimum: 1
            maximum: 210000
            type: integer
        - name: refId
          in: path
          required: true
          schema:
            type: string
        - name: refType
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/RefType"
      operationId: uploadImage
      requestBody:
        required: true
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfo'
        "400":
          description: Bad Request
    get:
      security:
        - oauth2: [ ocx-tn:all, ocx-tn:read ]
      tags:
        - imagesInternal
      description: Get an image by its reference id and type
      operationId: getImage
      parameters:
        - name: refId
          in: path
          required: true
          schema:
            type: string
        - name: refType
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/RefType"
      responses:
        "200":
          description: Image retrieved successfully
          content:
            image/*:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
    delete:
      security:
        - oauth2: [ ocx-tn:all, ocx-tn:delete ]
      tags:
        - imagesInternal
      description: Delete an image by its reference id and type
      operationId: deleteImage
      parameters:
        - name: refId
          in: path
          required: true
          schema:
            type: string
        - name: refType
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/RefType"
      responses:
        "200":
          description: Image deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageInfo'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-tn:all: Grants access to all operations
            ocx-tn:read: Grants read access
            ocx-tn:write: Grants write access
            ocx-tn:delete: Grants access to delete operations
  schemas:
    RefType:
      type: string
      enum: [ logo ]
    ImageInfo:
      type: object
      properties:
        id:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string