---
openapi: 3.0.3
info:
  title: onecx-tenant data import
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/tenant:
    post:
      operationId: importTenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  schemas:
    DataImport:
      type: object
      properties:
        tenants:
          $ref: '#/components/schemas/DataImportTenants'
    DataImportTenants:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportTenant'
    DataImportTenant:
      type: object
      properties:
        orgId:
          required: true
          type: string
        description:
          type: string