openapi: "3.0.2"
info:
  title: onecx-tenant-svc
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: TenantInternal
    description: Execute tenant CRUD operations
paths:
  /internal/tenant:
      get:
        tags:
          - TenantInternal
        summary: Get all Tenant maps by page number and page size
        operationId: getAllTenantMaps
        parameters:
          - name: pageNumber
            in: query
            schema:
              format: int32
              description: The number of page.
              default: 0
              type: integer
          - name: pageSize
            in: query
            schema:
              format: int32
              description: The size of page
              default: 100
              type: integer
        responses:
          "200":
            description: OK
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/ResponseTenantMaps"
      post:
        tags:
          - TenantInternal
        summary: Post new Tenant map
        operationId: createTenantMap
        requestBody:
          required: true
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateRequestTenantMap'
        responses:
          "201":
            description: Created
            headers:
              Location:
                required: true
                schema:
                  type: string
                  format: url
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RestException'
          "404":
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RestException'
  /internal/tenant/{id}:
      get:
        tags:
          - TenantInternal
        summary: Get Tenant map by GUID
        operationId: getTenantMapById
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        responses:
          "200":
            description: OK
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/ResponseTenantMap"
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RestException'
          "404":
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RestException'
      put:
        tags:
          - TenantInternal
        summary: Update Tenant map by GUID
        operationId: updateTenantMapById
        parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RequestTenantMap'
        responses:
          "200":
            description: OK
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/ResponseTenantMap"
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RestException'
          "404":
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RestException'

components:
  schemas:
    CreateRequestTenantMap:
      required:
        - InputTenantMap
      type: object
      properties:
        inputTenantMap:
          $ref: '#/components/schemas/CreateInputTenantMap'
    RequestTenantMap:
      required:
        - InputTenantMap
      type: object
      properties:
        inputTenantMap:
          $ref: '#/components/schemas/InputTenantMap'
    ResponseTenantMap:
      required:
        - TenantMap
      type: object
      properties:
        tenantMap:
          $ref: '#/components/schemas/TenantMap'
    ResponseTenantMaps:
      required:
        - TenantMap
      type: object
      properties:
        tenantMaps:
          type: array
          items:
            $ref: '#/components/schemas/TenantMap'
    CreateInputTenantMap:
      required:
        - orgId
      type: object
      properties:
        orgId:
          type: string
          description: Id of the organization
        tenantId:
          type: string
          description: Id of the tenant
    InputTenantMap:
      required:
        - orgId
      type: object
      properties:
        orgId:
          type: string
          description: Id of the organization
    TenantMap:
      type: object
      properties:
        orgId:
          type: string
          description: Id of the organization
        tenantId:
          type: string
          description: Id of the tenant
    RestException:
      type: object
      properties:
        errorCode:
          type: string
        message:
          type: string
        parameters:
          type: array
          items:
            type: object
        validations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationConstraint'
    ValidationConstraint:
      type: object
      properties:
        parameter:
          type: string
        message:
          type: string