openapi: "3.0.2"
info:
  title: onecx-tenant-svc
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: TenantInternal
    description: Execute tenant CRUD operations
paths:
  /internal/tenant:
      get:
        tags:
          - TenantInternal
        summary: Get all Tenant maps by page number and page size
        operationId: getAllTenantMapsPageable
        parameters:
          - name: pageNumber
            in: query
            schema:
              format: int32
              description: The number of page.
              default: 0
              type: integer
          - name: pageSize
            in: query
            schema:
              format: int32
              description: The size of page
              default: 100
              type: integer
        responses:
          "200":
            description: OK
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/ResponseTenantMaps"
      post:
        tags:
          - TenantInternal
        summary: Post new Tenant map
        operationId: createTenantMap
        requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RequestTenantMap'
        responses:
          "201":
            description: Created
          "400":
            description: Created
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
  /internal/tenant/{id}:
      put:
        tags:
          - TenantInternal
        summary: Update Tenant map by GUID
        operationId: updateTenantMapById
        parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RequestTenantMap'
        responses:
          "200":
            description: OK
          "404":
            description: Not found

components:
  schemas:
    RequestTenantMap:
      required:
        - InputTenantMap
      type: object
      properties:
        inputTenantMap:
          $ref: '#/components/schemas/InputTenantMap'
    ResponseTenantMap:
      required:
        - TenantMap
      type: object
      properties:
        tenantMap:
          $ref: '#/components/schemas/TenantMap'
    ResponseTenantMaps:
      required:
        - TenantMap
      type: object
      properties:
        tenantMaps:
          type: array
          items:
            $ref: '#/components/schemas/TenantMap'
    InputTenantMap:
      required:
        - orgId
      type: object
      properties:
        orgId:
          type: string
          description: Id of the organization
    TenantMap:
      type: object
      properties:
        orgId:
          type: string
          description: Id of the organization
        tenantId:
          type: integer
          description: Id of the tenant
    ErrorResponse:
      type: object
      properties:
        key:
          type: string
        parameters:
          type: array
          items:
            type: string
        details:
          type: array
          items:
            type: string